# Generated by Django 5.1.7 on 2025-04-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='jshr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
