# Generated by Django 5.1.7 on 2025-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_group_has_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='has_contract',
        ),
        migrations.AddField(
            model_name='student',
            name='has_contract',
            field=models.BooleanField(default=False),
        ),
    ]
