# Generated by Django 5.1.7 on 2025-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Naqt', 'Naqt'), ('Karta', 'Karta')], default='Naqt', max_length=10),
        ),
    ]
