# Generated by Django 5.1.7 on 2025-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_student_jshr_student_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
