# Generated by Django 5.1.7 on 2025-04-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_remove_group_has_contract_student_has_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course_name',
        ),
    ]
