# Generated by Django 5.1.7 on 2025-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_remove_group_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Naqt', 'Naqt'), ('Karta', 'Karta')], max_length=10, null=True),
        ),
    ]
