# Generated by Django 5.1.7 on 2025-05-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Naqt', 'Naqt'), ('Karta', 'Karta')], default='Naqt', max_length=10),
        ),
    ]
