# Generated by Django 5.1.7 on 2025-05-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0013_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='center.student'),
            preserve_default=False,
        ),
    ]
