# Generated by Django 5.1.7 on 2025-05-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0015_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
